// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: // Bu satırı ekle
        return android; // Bu satırı ekle
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaztjGO8CSepHiuxsFdMKKeC9uNYjTwpA',
    appId: '1:868455500626:web:306734f56d6900323ec88b',
    messagingSenderId: '868455500626',
    projectId: 'kasa-takip-7c650',
    authDomain: 'kasa-takip-7c650.firebaseapp.com',
    storageBucket: 'kasa-takip-7c650.firebasestorage.app',
    measurementId: 'G-QF9EK2M8C4',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'SENİN_API_KEY_İN',
    appId: '1:1234567890:android:abc123456', // Kendi App ID'ni yaz
    messagingSenderId: '1234567890', // Kendi Sender ID'ni yaz
    projectId: 'projenin-id-si',
    storageBucket: 'projenin-id-si.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOiAg8YBp1yOhk3SEvC5vXOwA_jS2NEH0',
    appId: '1:868455500626:ios:9407ceae2e3f48293ec88b',
    messagingSenderId: '868455500626',
    projectId: 'kasa-takip-7c650',
    storageBucket: 'kasa-takip-7c650.firebasestorage.app',
    iosBundleId: 'com.example.ilkUygulama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOiAg8YBp1yOhk3SEvC5vXOwA_jS2NEH0',
    appId: '1:868455500626:ios:9407ceae2e3f48293ec88b',
    messagingSenderId: '868455500626',
    projectId: 'kasa-takip-7c650',
    storageBucket: 'kasa-takip-7c650.firebasestorage.app',
    iosBundleId: 'com.example.ilkUygulama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaztjGO8CSepHiuxsFdMKKeC9uNYjTwpA',
    appId: '1:868455500626:web:0e2a4bb64b9b67de3ec88b',
    messagingSenderId: '868455500626',
    projectId: 'kasa-takip-7c650',
    authDomain: 'kasa-takip-7c650.firebaseapp.com',
    storageBucket: 'kasa-takip-7c650.firebasestorage.app',
    measurementId: 'G-FE0Y160NR9',
  );
}
